### ISSUE TITLE
executing 'gw' in non build directory throws NPE

### ISSUE THREAD

**Issue by gamerson** [david-truong/gw#1]
```
~ gw
Error executing gradle wrapper
java.lang.NullPointerException
    at com.liferay.gw.GradleExecutor.getExecutable(GradleExecutor.java:19)
    at com.liferay.gw.GradleExecutor.execute(GradleExecutor.java:57)
    at com.liferay.gw.GradleWrapper.main(GradleWrapper.java:13)
```

**Comment by david-truong** [comment]
fixed here: 283e297f0e56a5bef2344645076f53559bc66bd9
